# Generated by Django 4.2.5 on 2023-09-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidades',
            fields=[
                ('idComunidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreComunidad', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasella', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComunidad',
            fields=[
                ('idUsuarioComunidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('idComunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.comunidades')),
                ('idUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('idPublicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('idComunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.comunidades')),
                ('idUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('idComentario', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=150)),
                ('idPublicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.publicaciones')),
                ('idUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios')),
            ],
        ),
    ]
